#import "SGTranslate.h"

// The Spotify UI remains untouched. This table only covers strings emitted by the mod's own
// settings pages and the values those pages display, so a Korean build does not rewrite track,
// artist or account content supplied by Spotify.
NSString *SGTranslate(NSString *text) {
    if (!text.length) return text;

    static NSDictionary<NSString *, NSString *> *translations;
    static dispatch_once_t once;
    dispatch_once(&once, ^{
        translations = @{
            @"Mod": @"모드",
            @"Mod Settings": @"모드 설정",
            @"Appearance": @"외관",
            @"Redesigned UI": @"리디자인 UI",
            @"Redesigned": @"리디자인",
            @"Legacy": @"기존 UI",
            @"Player": @"플레이어",
            @"Player screen": @"플레이어 화면",
            @"Now playing": @"지금 재생 중",
            @"Now playing bar": @"지금 재생 중 바",
            @"Queue & devices": @"대기열 및 기기",
            @"Queue": @"대기열",
            @"Home": @"홈",
            @"Home & Library": @"홈 및 라이브러리",
            @"Library": @"라이브러리",
            @"Playlists": @"플레이리스트",
            @"Playlist": @"플레이리스트",
            @"Album": @"앨범",
            @"Albums": @"앨범",
            @"Artist": @"아티스트",
            @"Artists": @"아티스트",
            @"Navbar": @"탭 바",
            @"Tabs": @"탭",
            @"Lyrics": @"가사",
            @"Lyrics sources": @"가사 소스",
            @"Where lyrics come from": @"가사 제공처",
            @"Lyrics for every track": @"모든 트랙에 가사 표시",
            @"Name the source": @"가사 소스 이름 표시",
            @"Translation language": @"번역 언어",
            @"Uses a matching translation when a lyrics source provides more than one": @"가사 소스가 여러 번역을 제공할 때 일치하는 번역을 사용합니다",
            @"Automatic": @"자동",
            @"Korean": @"한국어",
            @"English": @"영어",
            @"Japanese": @"일본어",
            @"Chinese": @"중국어",
            @"Lyrics display": @"가사 표시 방식",
            @"Choose lyrics, translation and pronunciation/romanization rows": @"가사·번역·발음/로마자 행 표시 방식을 선택합니다",
            @"Lyrics only": @"가사만",
            @"Lyrics + translation + pronunciation": @"가사 + 번역 + 발음",
            @"Translation only": @"번역만",
            @"Pronunciation only": @"발음만",
            @"Alternate row order": @"보조 행 순서",
            @"Order the translation and pronunciation rows": @"번역과 발음 행의 순서를 정합니다",
            @"Pronunciation, then translation": @"발음, 다음 번역",
            @"Translation, then pronunciation": @"번역, 다음 발음",
            @"Replace artist with lyrics": @"아티스트 대신 가사 표시",
            @"Live Activity": @"라이브 활동",
            @"Lock screen widget": @"잠금 화면 위젯",
            @"Premium, ads & privacy": @"프리미엄·광고 및 개인정보",
            @"Premium": @"프리미엄",
            @"Ads": @"광고",
            @"Ads blocked so far": @"지금까지 차단한 광고",
            @"Upsells": @"업그레이드 안내",
            @"Tooltips": @"도움말",
            @"Reduce interventions": @"앱 내 안내 줄이기",
            @"All flags": @"모든 플래그",
            @"Labs": @"실험실",
            @"Artwork": @"아트워크",
            @"Header": @"헤더",
            @"Photo": @"사진",
            @"Vibrations": @"진동",
            @"Music Haptics": @"음악 햅틱",
            @"Taps and rumbles along with the music": @"음악에 맞춰 탭과 저음을 진동으로 재생합니다",
            @"The iPhone taps along with the drums and rumbles under the bass of whatever Spotify is playing, worked out from the sound as it plays, much like Music Haptics in Apple Music.\n\nIt follows Spotify's own speaker or headphone output, including while the screen is locked. Haptic events are driven at the strongest Core Haptics level; a song playing on another device through Connect has no local sound here to follow.": @"Spotify에서 재생 중인 음악의 드럼에 맞춰 탭하고 베이스에 맞춰 진동합니다. Apple Music의 음악 햅틱과 비슷하게 재생 중인 소리를 분석해 동작합니다.\n\n화면이 잠겨도 Spotify의 스피커 또는 헤드폰 출력을 따라갑니다. 햅틱 이벤트는 Core Haptics가 허용하는 가장 강한 수준으로 재생됩니다. Connect로 다른 기기에서 재생되는 곡은 이 기기에서 따라갈 소리가 없어 햅틱이 재생되지 않습니다.",
            @"Privacy": @"개인정보 보호",
            @"Accent colour": @"강조 색상",
            @"AMOLED background": @"AMOLED 배경",
            @"Pick a colour": @"색상 선택",
            @"Spotify's green": @"Spotify 그린",
            @"Spotify's own": @"Spotify 기본",
            @"Spotify's own tab": @"Spotify 기본 탭",
            @"Spotify's pages": @"Spotify 페이지",
            @"Anywhere else": @"기타 위치",
            @"Custom navbar": @"사용자 지정 탭 바",
            @"Add a tab…": @"탭 추가…",
            @"Add a Tab": @"탭 추가",
            @"Use Spotify's order": @"Spotify 순서 사용",
            @"Hidden": @"숨김",
            @"Show": @"표시",
            @"Off": @"끔",
            @"On": @"켬",
            @"Total": @"합계",
            @"Updates": @"업데이트",
            @"Version": @"버전",
            @"Website": @"웹사이트",
            @"GitHub": @"GitHub",
            @"Welcome tour": @"환영 안내",
            @"Export settings": @"설정 내보내기",
            @"Import settings": @"설정 가져오기",
            @"Reset all settings": @"모든 설정 초기화",
            @"Reset all settings?": @"모든 설정을 초기화할까요?",
            @"Reset and restart": @"초기화 후 재시작",
            @"Reset the counters": @"카운터 초기화",
            @"Reset the telemetry counters": @"텔레메트리 카운터 초기화",
            @"Start counting from zero": @"0부터 다시 계산",
            @"Cancel": @"취소",
            @"OK": @"확인",
            @"Later": @"나중에",
            @"Restart now": @"지금 재시작",
            @"Restart Spotify": @"Spotify 재시작",
            @"Start listening": @"감상 시작",
            @"Open GitHub": @"GitHub 열기",
            @"Report a bug": @"버그 신고",
            @"About": @"정보",
            @"About this switch": @"이 스위치 정보",
            @"Overridden by another setting": @"다른 설정에 의해 덮어써짐",
            @"Another switch is forcing this flag, so the row shows what it forces instead of taking a value of its own.": @"다른 스위치가 이 플래그를 강제하고 있어 이 항목은 자체 값 대신 강제된 값을 표시합니다.",
            @"Changes apply after you restart Spotify.": @"변경 사항은 Spotify를 재시작한 후 적용됩니다.",
            @"Changes apply after you restart Spotify. Gestures and Blocked artists apply straight away.": @"변경 사항은 Spotify를 재시작한 후 적용됩니다. 제스처와 차단한 아티스트는 즉시 적용됩니다.",
            @"Changes apply after you restart Spotify. Gestures, Blocked artists and Vibrations apply straight away.": @"변경 사항은 Spotify를 재시작한 후 적용됩니다. 제스처, 차단한 아티스트 및 진동은 즉시 적용됩니다.",
            @"The newest version of spoti.pw, leaning towards Apple Music's style. It is not compatible with the legacy look's settings.\n\nThe legacy look gives you more freedom, yet still looks like Spotify.": @"Apple Music 스타일에 가까운 spoti.pw의 최신 UI입니다. 기존 UI의 설정과 호환되지 않습니다.\n\n기존 UI는 더 많은 설정을 제공하면서도 Spotify의 모습을 유지합니다.",
            @"The redesign takes over when Spotify starts again. Spotify closes now; open it again to see it.": @"Spotify를 다시 시작하면 리디자인 UI가 적용됩니다. 지금 Spotify를 종료하므로 다시 열어 확인하세요.",
            @"Spotify's own look comes back when Spotify starts again. Spotify closes now; open it again to see it.": @"Spotify를 다시 시작하면 기본 UI로 돌아갑니다. 지금 Spotify를 종료하므로 다시 열어 확인하세요.",
            @"Pick your look.": @"사용할 UI를 선택하세요.",
            @"Looks like Apple Music. Better lyrics, Live Activity.": @"Apple Music처럼 보입니다. 더 나은 가사와 라이브 활동을 제공합니다.",
            @"More options, still looks like Spotify.": @"더 많은 설정을 제공하면서도 Spotify의 모습을 유지합니다.",
            @"Hold Home to open settings.": @"홈 탭을 길게 눌러 설정을 여세요.",
            @"The redesign is a beta. Expect lags, freezes and bugs, and if you find one, please report it.": @"리디자인 UI는 베타 버전입니다. 지연, 멈춤 및 오류가 발생할 수 있습니다. 문제를 발견하면 신고해 주세요.",
            @"Block telemetry": @"텔레메트리 차단",
            @"Answer the analytics endpoints with an empty reply instead of letting the request out": @"분석 요청을 전송하지 않고 빈 응답으로 처리합니다",
            @"Telemetry blocked so far": @"지금까지 차단한 텔레메트리",
            @"Hide ads": @"광고 숨기기",
            @"Hide upsells": @"업그레이드 안내 숨기기",
            @"Hide the video carousel in Search": @"검색의 동영상 캐러셀 숨기기",
            @"Hide social proof in Search": @"검색의 사회적 증거 숨기기",
            @"Ad and upsell flags": @"광고 및 업그레이드 플래그",
            @"Block the ad when the app opens": @"앱 실행 시 광고 차단",
            @"Block its CTA card": @"광고의 CTA 카드 차단",
            @"Hide the shuffle toggle upsell": @"셔플 전환 업그레이드 안내 숨기기",
            @"Hide the shuffle upsell in the video player": @"동영상 플레이어의 셔플 업그레이드 안내 숨기기",
            @"Hide the smart shuffle helper": @"스마트 셔플 도움말 숨기기",
            @"Hide the data saver tip": @"데이터 절약 팁 숨기기",
            @"Hide the player suggestions upsell": @"플레이어 추천 업그레이드 안내 숨기기",
            @"Hide the AI playlist creation tip": @"AI 플레이리스트 생성 팁 숨기기",
            @"Hide the watch feed explorer tip": @"Watch 피드 탐색 팁 숨기기",
            @"Hide the account switching tip": @"계정 전환 팁 숨기기",
            @"Hide the concert notifications tip": @"콘서트 알림 팁 숨기기",
            @"Hide the live event tip": @"라이브 이벤트 팁 숨기기",
            @"Hide the live event venue tip": @"라이브 이벤트 장소 팁 숨기기",
            @"Hide the Puffin nudge": @"Puffin 알림 숨기기",
            @"Spoof Premium": @"프리미엄 상태 모방",
            @"Your account remains unchanged; this only changes what the app sees.": @"계정 자체는 변경되지 않으며 앱이 보는 상태만 바꿉니다.",
            @"Controls": @"제어",
            @"Like and dislike buttons": @"좋아요 및 싫어요 버튼",
            @"Skip button on podcasts": @"팟캐스트 건너뛰기 버튼",
            @"Chapter skip controls": @"챕터 건너뛰기 제어",
            @"Burst skip": @"구간 건너뛰기",
            @"Animated artwork": @"애니메이션 아트워크",
            @"Video artwork": @"동영상 아트워크",
            @"Companion content": @"연동 콘텐츠",
            @"Gestures": @"제스처",
            @"Double tap here": @"여기를 두 번 탭하세요",
            @"Double tap the player": @"플레이어 두 번 탭하기",
            @"Start over": @"처음부터",
            @"Split": @"분할 방식",
            @"Seek step": @"탐색 단위",
            @"Nothing": @"없음",
            @"Seek back": @"뒤로 탐색",
            @"Seek forward": @"앞으로 탐색",
            @"Play or pause": @"재생 또는 일시정지",
            @"Next track": @"다음 트랙",
            @"Previous track": @"이전 트랙",
            @"Shuffle": @"셔플",
            @"Repeat": @"반복",
            @"Hide the device button": @"기기 버튼 숨기기",
            @"Two lines of track info": @"트랙 정보 두 줄 표시",
            @"Save button": @"저장 버튼",
            @"Queue badge": @"대기열 배지",
            @"Hold and drag to resize": @"길게 누른 후 드래그해 크기 조절",
            @"Video in the mini player": @"미니 플레이어에 동영상 표시",
            @"Bar to cover art animation": @"바에서 커버 아트로 전환 애니메이션",
            @"Mini player transition animations": @"미니 플레이어 전환 애니메이션",
            @"Artwork background": @"아트워크 배경",
            @"Glass header buttons": @"글래스 헤더 버튼",
            @"Disable Canvas": @"Canvas 비활성화",
            @"Sheet style player": @"시트 스타일 플레이어",
            @"Redesigned header": @"리디자인 헤더",
            @"New progress slider": @"새 진행 슬라이더",
            @"Expand the sticky header on tap": @"탭하여 고정 헤더 펼치기",
            @"Hide cards below the player": @"플레이어 아래 카드 숨기기",
            @"About the artist": @"아티스트 정보",
            @"Related videos": @"관련 동영상",
            @"Lyrics preview": @"가사 미리보기",
            @"Add to playlist": @"플레이리스트에 추가",
            @"Share": @"공유",
            @"Connect to a device": @"기기에 연결",
            @"Glass lyrics": @"글래스 가사",
            @"Bottom sheets": @"하단 시트",
            @"Queue as a bottom sheet": @"대기열을 하단 시트로 표시",
            @"Connect as a bottom sheet": @"연결 화면을 하단 시트로 표시",
            @"Connect sheet from the video switcher": @"동영상 전환기에서 연결 시트 열기",
            @"Queue flip transition": @"대기열 뒤집기 전환",
            @"Play next in the context menu": @"컨텍스트 메뉴에서 다음에 재생",
            @"Where the tab goes, and the glyph on it.": @"탭이 열 페이지와 탭 아이콘입니다.",
            @"Drag a tab by the handle to move it, tap it to show or hide it. The bar follows straight away.": @"핸들을 드래그해 탭을 이동하고, 탭을 눌러 표시하거나 숨기세요. 탭 바에 즉시 반영됩니다.",
            @"A page of Spotify's, or any link": @"Spotify 페이지 또는 임의의 링크",
            @"Forgets the order and the tabs you added": @"순서와 추가한 탭을 모두 초기화합니다",
            @"A name, a URI of your own and an icon": @"직접 지정한 이름·URI·아이콘",
            @"Gradient": @"그라데이션",
            @"Off leaves Home the way Spotify draws it": @"끔으로 설정하면 Spotify 기본 홈 화면을 사용합니다",
            @"Colour": @"색상",
            @"Strength": @"강도",
            @"Height": @"높이",
            @"Denser rows": @"더 촘촘한 행",
            @"Sort playlists by recently updated": @"최근 수정 순으로 플레이리스트 정렬",
            @"Sort artists by recently updated": @"최근 수정 순으로 아티스트 정렬",
            @"Recents": @"최근 항목",
            @"Recents sort order": @"최근 항목 정렬 순서",
            @"Library settings": @"라이브러리 설정",
            @"Library Pro": @"라이브러리 Pro",
            @"Pull to refresh": @"당겨서 새로고침",
            @"Filter pills": @"필터 버튼",
            @"Shortcuts grid": @"바로가기 그리드",
            @"Promo cards": @"프로모션 카드",
            @"Preview cards": @"미리보기 카드",
            @"DJ card": @"DJ 카드",
            @"DJ button": @"DJ 버튼",
            @"DJ beta badge": @"DJ 베타 배지",
            @"Hide in the header": @"헤더에서 숨기기",
            @"Hide in the playlist header": @"플레이리스트 헤더에서 숨기기",
            @"Hide on the page": @"페이지에서 숨기기",
            @"Hide on Home": @"홈에서 숨기기",
            @"Hide on the player": @"플레이어에서 숨기기",
            @"Hide playlist buttons": @"플레이리스트 버튼 숨기기",
            @"Hide above the tracks": @"트랙 위에서 숨기기",
            @"Cover artwork": @"커버 아트",
            @"Description": @"설명",
            @"Creator and collaborators": @"제작자 및 협업자",
            @"Length and saves": @"길이 및 저장 수",
            @"Video": @"동영상",
            @"Download": @"다운로드",
            @"More": @"더 보기",
            @"More options": @"추가 옵션",
            @"Curation pills": @"큐레이션 버튼",
            @"Find and sort bar": @"찾기 및 정렬 바",
            @"Fade into a blur": @"흐림 효과로 전환",
            @"Explore (video deck)": @"탐색(동영상 덱)",
            @"Follow": @"팔로우",
            @"Verified badge": @"인증 배지",
            @"Monthly listeners": @"월간 청취자",
            @"Hide the tab bar": @"탭 바 숨기기",
            @"Songs you liked": @"좋아요 표시한 곡",
            @"Popular": @"인기",
            @"Artist pick": @"아티스트 추천",
            @"Popular releases": @"인기 릴리스",
            @"Featuring": @"피처링",
            @"Music videos": @"뮤직비디오",
            @"Artist playlists": @"아티스트 플레이리스트",
            @"Fans also like": @"팬들이 함께 좋아하는 항목",
            @"Appears on": @"참여 앨범",
            @"Discovered on": @"발견된 위치",
            @"Share button in the header": @"헤더의 공유 버튼",
            @"More options in the navigation bar": @"탐색 바의 추가 옵션",
            @"Top collaborators": @"주요 협업자",
            @"Artist facts": @"아티스트 정보",
            @"Asked in this order": @"이 순서로 요청",
            @"None on": @"활성화된 항목 없음",
            @"Name": @"이름",
            @"Icon": @"아이콘",
            @"Create": @"생성",
            @"Any link": @"임의의 링크",
            @"Any link…": @"임의의 링크…",
            @"Block": @"차단",
            @"Blocked": @"차단됨",
            @"Blocked Artists": @"차단한 아티스트",
            @"Unblock": @"차단 해제",
            @"Skip when the artist is": @"아티스트 건너뛰기 조건",
            @"Their tracks are skipped as soon as they start": @"해당 아티스트의 트랙은 시작하자마자 건너뜁니다",
            @"Main or featured": @"메인 또는 피처링",
            @"The main artist": @"메인 아티스트",
            @"The first name on the track": @"트랙에 표시된 첫 번째 이름",
            @"Any credit on the track": @"트랙의 모든 크레딧",
            @"Shows": @"표시 내용",
            @"On the lock screen and in the Dynamic Island": @"잠금 화면 및 다이내믹 아일랜드",
            @"With no source on, Spotify's own lyrics are left alone.": @"모든 소스를 끄면 Spotify 기본 가사를 그대로 사용합니다.",
            @"Offers the lyrics card on tracks Spotify has no lyrics for; needs a source above": @"Spotify에 가사가 없는 트랙에도 가사 카드를 표시합니다. 위의 가사 소스가 필요합니다.",
            @"Reads out which source the lines on the full screen page came from": @"전체 화면에 표시되는 가사의 출처를 보여줍니다",
            @"The line being sung shows in place of the artist, so lyrics show up on the lock screen and in CarPlay": @"현재 부르는 가사를 아티스트 이름 대신 표시해 잠금 화면과 CarPlay에서도 가사를 볼 수 있습니다",
            @"Spotify's flags": @"Spotify 플래그",
            @"Spotify green": @"Spotify 그린",
            @"Teal": @"청록색",
            @"Blue": @"파란색",
            @"Indigo": @"남색",
            @"Purple": @"보라색",
            @"Pink": @"분홍색",
            @"Red": @"빨간색",
            @"Amber": @"호박색",
            @"Subtle": @"약하게",
            @"Medium": @"중간",
            @"Bold": @"강하게",
            @"Short": @"짧게",
            @"Tall": @"높게",
            @"The whole screen": @"전체 화면",
        };
    });

    NSString *translated = translations[text];
    if (translated) return translated;
    if ([text hasSuffix:@" seconds"]) {
        return [[text substringToIndex:text.length - 8] stringByAppendingString:@"초"];
    }
    if ([text hasSuffix:@" (featured)"]) {
        return [[text substringToIndex:text.length - 11] stringByAppendingString:@" (피처링)"];
    }
    return text;
}
